# TODO: Add dialogue for this scene (this might take a long time)
# TODO: Add music, sound effects, and background art (Im broke T^T)

label prologue:

# Beginning Scene
    "Have you ever dreamed so vividly it felt less like fantasy and more like a memory?"
    "Not dragons or flying cars"
    "Just a quiet moment you swear could've happened yesterday or might happen tomorrow."
    "In my dream, I'm standing in the rain. No umbrella. No shelter."
    "The cold seeps through my hoodie as neon signs flicker around me like broken pixels and headlights smear past like ghost data."
    "My phone is dead, and my resume lies damp and crumpled in my bag"
    "I'd just come from another interview. Another polite rejection. Another reminder that the game I wanted to build"
    "Something beautiful, something that made people feel seen"
    "Was still out of reach"
    "All I had was a soaked hoodie, a half-finished portfolio, and the creeping doubt that maybe I wasn't good enough"
    "Then"
    "She appeared. No fanfare, no slow-motion, just a stranger stepping beside me, holding out her umbrella, and smiling."
    "We walked together through the rain, her presence calm, like a loading screen that didn't rush you"
    "I didn't know her name. I didn't ask"
    "I just remembered the warmth of shared silence and how her umbrella tilted toward me, making space for more than just my body"
    "We reached my doorstep. I turned to thank her, but she was already walking away, no name, no goodbye, just a smile that felt like a soft reboot"
    "As she disappeared into the storm, for the first time in weeks I felt something other than exhaustion. I felt hope."
# Wake up screen transition
    "I wake to the soft click of my alarm and the pale light of morning. The rain is gone and the dream slips away, but its promise lingers"
    "Today is my first day at Studio Kairo. A real dev team. A real chance. I don't know who she is, but maybe she's out there somewhere in the code of my life, waiting to be compiled"
    main "What a strange dream..."
    "I open my eyes to a new day, the weight of the past lifting slightly, replaced by the tentative hope of what could be"
    "What should I do first? What should I wear today? What should I eat for breakfast?"
    "Normally, these questions would be trivial, but today they feel like the first lines of a new script"
    "A script where maybe, just maybe, I won't be alone"
    main "Alright, no time for daydreaming. Let's get breakfast and head to the studio."
    "Well... easier said that done - my fridge is completely empty."
    main "What the heck? I could've sworn I went grocery shopping last week."
    main "Guess I'll have to swing by the convenience store on the way."
    "I plan to choose a simple outfit - jeans, a hoodie, and my favorite sneakers. Practical, comfortable, and ready for whatever the day might throw at me."
    main "I think I should choose something bright. Maybe it'll help me stand out a bit on my first day."
    "Atleast that what I said, but I ended up choosing a plain white t-shirt and a light blue hoodie."
    "I'm still a student after all, I don't want to look too flashy."
    main "I'm good now. Time to head out."
    "I grab my bag, wallet, and keys, and head out the door."
    "The rain has stopped, but the sky is still overcast, and the air smells like wet pavement and fresh starts."
    "As I walk to the convenience store, I can't help but feel a little nervous."
    main "What if I mess up? What if they don't like me? What if I can't keep up?"
    "But then I remember the dream. The stranger with the umbrella. The hope she gave me."
    main "Maybe this is my chance. My chance to prove myself. To show them what I'm made of."
    "I take a deep breath and quicken my pace, eager to get to the store and pick up some breakfast."
    "If I'm lucky, maybe I'll even run into that stranger again."
    "That is never happening, you idiot."
    "I chuckle to myself and shake my head, trying to push the thought out of my mind."
    "After taking some energy bars and a bottle of water, I leave the store and head towards the Bunkaido Train Station."
    "I talked a big game about getting breakfast, but all I had was enough loose change for a couple of energy bars and a bottle of water."
    "Not exactly the fuel of champions—but it would have to do."
    "I walked to the station, the cold air waking me up more than the food ever could."
    "The train rocks beneath my feet, a reminder that the world spares no one."
    "I clutch my messenger bag—inside: a cleaned-up laptop, a USB drive with my demo reel, and a regrettable convenience-store sandwich."
    "Studio Kairo. Just saying it makes everything feel more real. Their ad hadn't promised stability or big bucks, only one line: “Help us build something that feels like a memory."
    "So I applied, not expecting anything. This time, someone answered."


    jump chapter0

label chapter0:    
    "A small building squeezed between a vape shop and a laundromat greets me."
    "A broken neon sign reads “D EAM FRESH,” which somehow feels fitting."
    main "Dream Fresh? More like Dream Mess."
    "I laugh at my own stupid joke, the sound a little too loud in the quiet street."
    main "Alright, time to see if I can actually do this."
    "Third floor. No elevator. Sticky stairs. The smell of instant noodles and stale coffee intensifies as I climb"
    "I reach the top, heart pounding, palms sweaty."
    "I take a deep breath and push open the door."
    "Just as I reach for the handle, the door swings open on its own."
    "A wild-haired guy with mismatched socks greets me"
    "Wild-haired guy" "You must be the new dev! We didn't order dumplings, right?"
    "What a terrible first impression."
    "He laughs, a sound that feels more like a nervous tick than genuine amusement."
    "I think he is 20s, maybe early 30s. His clothes are a mess, and he has a permanent five o'clock shadow."
    "He looks like he hasn't slept in days, which, judging by the state of the office, is probably true."
    "His eyes are bloodshot, and he blinks like sleep is a distant memory. The office mirrors him—half-empty ramen cups, tangled wires, and a whiteboard that looks like it lost a fight with a marker."
    main "I'm not the delivery guy. I'm Hiroshi, the new dev."
    "He squints at me, then breaks into a grin."
    "Wild-haired guy" "Nice to meet you, Hiroshi! I'm Tomo, the lead developer in the team."
    main "Nice to meet you too, Tomo. This place is... something else."
    "Tomo chuckles, a sound that feels more like a nervous tick than genuine amusement."
    t "Chaos is our secret sauce. If it ain't messy, it ain't magic."
    "I nod, trying to ignore the pile of empty ramen cups and soda cans that seem to be multiplying on their own."
    t "Let me introduce you to the team. They're probably in the back, working on the new project."
    "I follow Tomo through the cluttered office, trying to ignore the sticky floor and the faint smell of burnt popcorn."
    "This is not the type of place I imagined when I thought about working in game development."
    "But maybe that's a good thing. Maybe this chaos is where creativity thrives."
    "We reach the back of the office, where a group of people are huddled around a table, deep in discussion."
    "Inside is glorious chaos: unfinished game posters, whiteboards screaming “FIX THE DAMN WATER PHYSICS,” beanbags instead of chairs, and a shark-onesie coder furiously hacking like he's in the Matrix. “Hey everyone, new dev!"
    "Cue a chorus of hellos, one accidental burp, and someone yelling 'Did anyone feed the server hamster?!"
    "This is not gonna be easy."
    "I gulp down my nerves and step forward."
    "Not today. Today, I dive headfirst into the madness—and maybe, just maybe, find my place in it."
    jump scene1

    #This thing can be improved later, I just want to finish the script first

# Scene 1: Studio Entrance
label scene1:
    "Somehow, I luckily made it through the morning without completely embarrassing myself."
    "That is a big success for me as a new worker right?"
    "*grrr* *grrr*"
    "My stomach growls loudly, reminding me that I haven't eaten since those sad energy bars."
    "Man, I should've brought more food."
    "But I never expected to think my first day would be this hectic."
    "However, it kinda fun too."
    main "Alright, time to head out for lunch. Maybe I'll find something decent around here."
    "I say bye to Tomo and the team, grabbing my bag and heading out the door."
    "When I step outside, the sky has darkened, and rain starts to fall."
    "Great. Just great."
    "I pull out my phone to check the weather app, but of course, my battery is dead."
    main "What a coincidence!!!"
    "I look around, took my umbrella from my bad, and started walking."
    "The rain is coming down harder now, and I can feel the cold seeping through my hoodie."
    main "I must be hurry, or I'll be soaked."
    "I step down the street, the rain create a rhythmic pattern on the pavement."
    "And some puddle as well."
    "I carefully navigate around them, trying to keep my shoes dry."
    "As I turn a corner, I almost bump into someone." # Can be improved later
    main "Oh, sorry about that"
    "I look up to see a girl with a bright umbrella, her expression a mix of surprise and amusement."
    k "Watch where you're going!"
    main "Right, my bad. Thanks for the warning."
    k "And for the record, you might want to invest in a better umbrella."
    main "Yeah, I'll add it to my shopping list."
    "After a brief moment of awkward silence, she walks away, leaving me standing in the rain." # ?
    main "Wait, I didn't even get her name."
    main " *sign* Let's forget it. I need to get something to eat first."
    "I continue walking, the rain soaking through my clothes despite my best efforts."
    "After a few blocks, I spot a small restaurant with a cozy-looking interior."
    main "I have never been here before. Maybe it's worth a try."
    "I step inside, grateful for the warmth and shelter from the rain."
    "The smell of food and the sound of chatter fill the air, making me feel a little less alone."
    "I order a takeout bento box and go back to the studio."
    "That costs me around 800 yen, that's kinda expensive for a student like me."
    "You get what you pay for, I guess....?"
    "As I step back outside, the rain has let up a bit, but the sky is still gray and overcast."
    main "I should probably head back before it starts pouring again."
    "I start walking, the bento box in my hand and my mind on the strange encounter from earlier."
    "After a few minutes, I hear footsteps behind me."
    "I turn to see the girl from earlier, the one with the bright umbrella."
    k "Hey, you're the guy from earlier, right?"
    main "And you are the girl from earlier, right?"
    k "Yeah, that's me. I saw you heading back to the studio. Thought you might need some company."
    main "That's very kind of you. Thanks."
    "We walk together in silence for a few moments, the sound of rain tapping on the umbrella above us."
    main "So, uh, thanks for the umbrella. I really appreciate it."
    k "No problem. It's the least I could do."
    main "By the way, I'm Hiroshi. I just started working at Studio Kairo today."
    k "Nice to meet you, Hiroshi. I'm Kasuka."
    main "Nice to meet you too, Kasuka."
    "We continue walking, the rain easing up as we go."
    main "So, do you work around here?"
    k "Try to guess."
    "Girl is mysterious, I don't understand at all."
    "If you give me 2 hours to understand girls or code, I would choose the code every time."
    "It's easy to understand a complex code than a girl."
    "That's just how I am."
    main "Hmm, let me think. You seem like someone who enjoys art and creativity."
    k "Close enough. Continue to guess."
    main "HMMMMMMMMMMMMM, that is a tough one. Maybe you're a graphic designer or an illustrator?"
    k "Bingo. You are right."
    main "Wow, I didn't expect to get it right."
    "That's all ?"
    "I expected something more complicated."
    "Well, I guess girls are not that complicated after all."
    k "You seem surprised."
    main "A little. I guess I had this idea that artists were all a bit eccentric and unpredictable."
    k "Eccentric? Unpredictable? Maybe a little. But I like to think of myself as more grounded than that."
    main "Well, you definitely seem down-to-earth."
    k "Thanks. I try to be."
    main "So, what kind of art do you do?"
    k "Mostly digital illustration and character design. I love creating worlds and stories through my art."
    main "That sounds amazing. I've always admired people who can bring their imagination to life like that."
    k "It's a lot of fun, but it can also be challenging. Sometimes I struggle with creative blocks or self-doubt."
    main "I can relate to that. As a developer, I often face similar challenges when trying to solve complex problems or debug code."
    k "Yeah, I think creativity in any form comes with its ups and downs."
    main "Definitely."
    "We walk in comfortable silence for a few more minutes, the rain now just a light drizzle."
    "What is this awkward silence?"
    "I don't know what to say anymore."
    "I feel like I should say something, but I don't want to come across as desperate or needy."
    "Maybe I should just let the silence be."
    "But then again, maybe I should try to keep the conversation going."
    main "So, uh, do you come to this area often?"
    k "Yes, I work at a studio nearby. It's a nice area with lots of good food and coffee shops."
    "Huh? She works at a studio nearby?"
    "What are the odds of that?"
    main "Oh, really? What kind of studio?"
    k "It's a small indie game studio. We mostly work on mobile games and visual novels."
    "Sounds familiar."
    "I wonder if I've heard of them before."
    main "That's cool. I've always been interested in game development."
    k "Yeah, it's a fun industry to be in. Lots of creativity and innovation."
    main "I just started working at Studio Kairo today. It's my first job in the industry."
    k "....."
    main "Is something wrong?"
    k "No, it's just... I didn't expect to meet someone from Studio Kairo here."
    "Is that a bad thing?"
    "I don't know. It's just... complicated."
    "Or I don't understand at all...."
    "I remain silent, unsure of what to say next."
    "This is the consequence of being a nerd and full-time at home gamer."
    "I would have socialized more in the past"
    "That is what I thought."
    "Realize the situation now, it is too late."
    "I should have been more social when I had the chance."
    "Now, I am stuck in this awkward situation."
    k "Look, I'm sorry if I made things weird. I just... I don't know. It's complicated."
    main "It's okay. I understand. We can just walk in silence if you want."
    k "Yeah, that sounds good."
    "We continue walking in silence, the rain now just a light drizzle."
    "After a few minutes, we reach the studio building."
    main "Well, this is me. Thanks for walking me back."
    k "No problem. It was nice meeting you, Hiroshi."
    main "You too, Kasuka. Maybe I'll see you around."
    k "Maybe."
    "She turns and walks away, leaving me standing in front of the studio."
    main "Well, that was... interesting."
    "I take a deep breath and head inside, ready to face whatever the rest of the day might bring."
    "I can't help but wonder if I'll ever see Kasuka again."
    "Maybe it's best not to think about it too much."
    "I have more thing to work in the afternoon after all."
    main "Alright, time to get back to work."
    main "I will show them that I am capable of doing this job."
    "That is what I thought."
    "When I open the door, I hear a loud, very loud screaming from inside."
    main "What the heck is going on in there?"
    "I walk in to see Tomo and the team gathered around a computer, their faces looking panicked."
    main "Is everything okay?"
    t "Hiroshi, thank god you're here. We have a huge problem."
    main "What kind of problem?"
    t "someone spills miso on a company laptop."
    "?"
    "Is that a big deal?"
    "Just a little miso, right?"
    main "Miso? On a laptop? How bad is it?"
    "I can't believe this is happening."
    "What kind of idiot spills miso on a laptop?"
    t "It's pretty bad. The laptop is completely soaked, and we can't turn it on."
    main "So...?"
    t "That laptop is the only copy of our game demo. We have a big meeting with a potential investor tomorrow, and if we can't show them the demo, we're screwed."
    "We all look at each other, the weight of the situation sinking in."
    "I know one thing for sure."
    "We are fucked."
    "Everyone is panicking, trying to figure out what to do."
    "Then suddenly, a familiar voice speaks up."
    k "Don't worry, use rice—it absorbs moisture better than panic."
    "I look up and meet Kasuka's steady gaze"
    "Why is she here again?"
    main "Kasuka? What are yo—"
    "Unable to finish my sentence, she steps forward and takes charge of the situation."
    k "First, we need to turn off the laptop and unplug it. Then, we'll remove the battery and any other removable parts."
    "She moves with confidence, her hands steady despite the chaos around her."
    k "Next, we'll use a soft cloth to blot away as much of the miso as possible. Be gentle, we don't want to push the liquid further into the laptop."
    "Everyone watches in silence as she works, her focus unwavering."
    k "Now, we'll use some uncooked rice to help absorb the remaining moisture. Just pour a generous amount into a sealable plastic bag, then place the laptop inside and seal it up."
    "She finishes her instructions and looks up, her expression calm and reassuring."
    k "Leave it in the rice for at least 24 to 48 hours. The rice will help draw out the moisture and hopefully save the laptop."
    "I can't believe how calm and collected she is."
    main "..."
    "I cannot find the words to express my gratitude."
    "Kasuka is so professional and knowledgeable."
    "I feel a mix of admiration and relief wash over me."
    t "Thank you, Kasuka. We really appreciate your help."
    k "No problem. I'm just glad I could help."
    "She smiles warmly"
    "But why is she here again?"
    "I still don't understand."
    "After Kasuka leaves, we follow her advice and place the laptop in a bag of rice."
    "We all hope for the best, knowing that our future as a studio might depend on it."
    "As we work, I can't help but think about Kasuka and the strange coincidence of meeting her again."
    "Maybe it's fate, or maybe just a random twist of luck."
    "Either way, I'm grateful for her help and the unexpected connection we've made."
    "I just hope we can save the laptop and keep our dream alive."
    "After a few hours of frantic work, we finally manage to salvage the laptop."
    "It takes some time, but eventually, we get it working again."
    main "Let me test it out."
    t "Go ahead."
    "I take a deep breath and power on the laptop."
    "To our relief, it boots up without any issues."
    "We quickly check the demo, and everything seems to be intact."
    main "It's working! The demo is still here!"
    t "Thank god. I don't know what we would have done without Kasuka's help."
    "We all let out a collective sigh of relief, the tension in the room finally easing."
    "I can't help but feel a sense of pride and accomplishment."
    "Despite the chaos and uncertainty, we managed to pull through."
    "And maybe, just maybe, we have a chance at making our dream a reality."
    main "Huh ?"
    t "What's wrong?"
    main "Nothing, just thinking about how crazy this day has been."
    "I realize there is a strange log in the server."
    "It looks like someone has been accessing files they shouldn't have."
    main "Tomo, can you check the server logs? I think someone might have been accessing files they shouldn't have."
    t "Sure, let me take a look."
    "Tomo sits down at the computer and starts typing furiously."
    "After a few minutes, he looks up, his expression serious."
    t "Hiroshi, you have to see this."
    main "What is it?"
    "I look over his shoulder and see the server logs."
    "There is a line that stands out."
    " #Kasuka was here"
    "What the heck does that mean?"
    main "Tomo, what does this line mean? 'Kasuka was here'?"
    t "I have no idea. It looks like someone added it to the logs manually."
    t "But why would Kasuka do that?"
    main "I don't know. Maybe someone is trying to mess with us."
    t "This is really strange. We need to find out who did this."
    main "Yeah, we do."
    "We spend the next hour digging through the server logs, trying to find any clues."
    "But we don't find anything else out of the ordinary."
    t "This is really weird. I don't know what to make of it."
    t "But anyway, we should probably focus on getting the demo ready for tomorrow."
    t "And you should return to your work now."
    main "Got it. See you again"
    "I nod and head back to my desk, my mind racing with questions and theories."
    main "Alright, time to get back to work."
    "I take a deep breath and focus on the task at hand, determined to prove myself and make the most of this opportunity."
    "Then suddenly, the power goes out."
    "What the heck is going on in this studio?"
    "I hear a loud crash from the back of the room, followed by a string of curses."
    main "What was that?"
    t "I don't know, but it sounded like it came from the server room."
    main "The server room? That's where we keep all our important files and data."
    t "We need to check it out. Hiroshi, can you come with me?"
    main "Sure, let's go."
    "We make our way to the server room, the darkness making it hard to see."
    "As we enter, we see one of our team members, Daichi, lying on the floor, surrounded by a mess of cables and equipment."
    main "Daichi! Are you okay?"
    "Daichi Kanabe - The lead programmer of the team. A bit of a perfectionist, but a genius when it comes to coding."
    d "Ugh... I'm fine. Just a little shaken up."
    main "What happened?"
    d "I was trying to fix the backup generator when I accidentally tripped over a cable and fell."
    t "We need to get you some help. Can you stand?"
    d "Yeah, I think so. Just need a moment."
    "With some assistance, Daichi manages to get back on his feet."
    main "We should probably get you to a hospital, just to be safe."
    d "No, I'm fine. Just a few bruises. I'll be okay."
    t "Are you sure? We can call an ambulance if you need it."
    d "No, really. I'm fine. Just need to sit down for a bit."
    main "Alright, but if you start feeling worse, we need to get you checked out."
    d "Thanks, Hiroshi. I appreciate it."
    "We help Daichi to a nearby chair, and he sits down, still looking a little dazed."
    main "What about the server? Is everything okay?"
    d "I think so. I didn't see any major damage, but we should probably run some diagnostics just to be sure."
    t "Good idea. Let's get to work."
    "As we start checking the server, I can't help but feel a little overwhelmed."
    "This job is turning out to be a lot more complicated than I expected."
    "But I also feel a sense of excitement and purpose."
    "Maybe this is where I belong after all."
    main "Alright, let's get this server back up and running."
    "I take a deep breath and focus on the task at hand, determined to prove myself and make the most of this opportunity."
    "The day is far from over, and I have a feeling that things are only going to get more interesting from here."
    
    jump rainscene


label rainscene:
    "Well, that was a hectic afternoon."
    "But at least we managed to save the server and get things back on track."
    "I glance at the clock and realize it's already late afternoon."
    main "I should probably head home soon. It's been a long day."
    "As I gather my things and prepare to leave, I look out the window and see that the rain has started again."
    "My luck is unbelievable."
    main "Great. Just great."
    "I open my bag to grab my umbrella, only to find that it's missing."
    main "No way. I must have left it at the restaurant."
    "I sigh, realizing that I'm going to have to walk home in the rain without any protection."
    main "I guess I'll just have to tough it out."
    main "But don't worry, I am used to walking in the rain."
    "Alone"
    "That is what I used to be"
    "I can remember the days when I would walk home alone in the rain, feeling the cold drops soak through my clothes and chill me to the bone."
    "But"
    "No one is there to take care of me anymore."
    "I am all alone."
    "My parents are gone, my friends are busy with their own lives, and I have no one to turn to."
    "I am a lone wolf, a solitary figure in a world that seems to have forgotten me."
    "I have always been independent, relying on myself to get through the tough times."
    "I used to it."
    "In the time I ready to leave, I hear a familiar voice behind me."
    k "Are you sure you don't want to wait for the rain to let up? Or you are just a dumbass trying to walk home in this weather?"
    "Sighing, I turn around to face Kasuka."
    main "I'm fine, really. I can handle a little rain."
    k "I don't think so ? You are gonna catch a cold badly."
    main "Besides, I kind of like the rain."
    k "Are you a stubborn ?"
    main "Maybe a little."
    k "Well, if you really a stubborn, then atleast you can borrow my umbrella."


# Choices for Scene 1

label kasuka_walk_home_choice:
    menu:
        "Thank for the umbrella. You're really thoughtful.":
            $ flag_walk_home = True
            $ kasuka_affection += 1
            jump choices1_a

        "I could've handled it myself.":
            jump choices1_b

label choices1_a:
    main "Thanks for the umbrella. You're really thoughtful." # Finally I can cry *dev*
    k "Don't mention it! I just wanted to make sure you didn't get soaked."
    main "You are kind-hearted, Kasuka"
    k "Well, I try my best."
    main "It's nice to have someone like you around."
    k "What....."
    "Kasuka looks taken aback, her cheeks slightly flushed."
    "Did I say something wrong?"
    main "No, I just mean... it's nice to have someone to talk to. Someone who cares."
    k "I see..."
    "She looks down, her expression unreadable."
    "I think my words are normal, right?"
    "Maybe I should have said something different."
    "But what?"
    "I don't want to make her uncomfortable."
    "Maybe I should just change the subject."

    jump choices_common

label choices1_b:
    main "I could've handled it myself. Besides, I kind of like the rain." # Stubborn as always
    k "Well, if you say so, then I won't force you."
    "Kasuka remains silent, her expression unreadable."
    "Did I say something wrong?"
    "I dont think there is nothing wrong with what I said."
    "Maybe she is just not in the mood to talk."
    "I should just let it be."

    jump choices_common

# Continue the story flow

label choices_common:
    main "Anyway, thanks again for walking me back earlier. I really appreciate it."
    k "Don't mention it. It was nice to have some company."
    main "Yeah, it was. Maybe we can do it again sometime."
    k "Hmmmmmm"
    "Did I say something wrong again?"
    "Kasuka remains silent, her expression unreadable."
    main "Is something wrong?"
    k "It's nothing. Just... I don't know. It's complicated."
    main "If you say so."
    main "Then, I should probably get going. It's getting late."
    main "See you again, Kasuka."
    k "Yeah, see you."
    "I nod and head out into the rain, the umbrella shielding me from the worst of the downpour."
    "As I walk, I can't help but feel a little grateful for Kasuka's kindness."
    "Maybe this is the start of a new friendship."
    "Or maybe something more."
    "Either way, I know that I'm not alone anymore."
    "I just hope I can live up to her expectations."
    "The walk home is long and tiring, but the umbrella keeps me dry."
    "I think about the events of the day, the chaos at the studio, and the strange coincidence of meeting Kasuka again."
    "Maybe it's fate, or maybe just a random twist of luck."
    "Either way, I'm grateful for her help and the unexpected connection we've made."
    "When I finally reach my apartment, I'm soaked to the bone, but at least I'm not cold."
    main "Thanks again for the umbrella, Kasuka. I really appreciate it."
    "I take a deep breath and head inside, ready to dry off and get some rest."
    "As I close the door behind me, I can't help but wonder what tomorrow will bring."
    "Maybe, just maybe, things are starting to look up."
    "Huh?"
    "Then suddenly, I remember something."
    "Kasuka said something about the studio being nearby."
    "And the umbrella she gave me is pretty fancy."
    "Could it be?"
    "I quickly check the umbrella and see a small logo on the handle."
    "It's the logo of our studio."
    "And the game logo is our studio game."
    "Chrono Drift—a game me and the team have been working."
    "That is the first task I was assigned to do today—my first day as well."
    main "No way. Kasuka works at Studio Kairo?"
    "I can't believe it."
    "I feel a mix of excitement and nervousness wash over me."
    main "I have to find out more about her."
    "I try to wake up but I can't."
    "I am too tired."
    "Today was a long day after all."
    "There is many things happened."
    "These dirty studio, the broken laptop, the spilled miso, the power outage, and now this."
    "I just want to sleep."
    "I lay down on my bed, the events of the day swirling in my mind."
    "As I close my eyes, the dream from this morning comes back to me."
    "But this time, it's different."
    "This time, I see Kasuka standing beside me"
    "We are at the cherry blossom park near the studio."
    "The rain has stopped, and the sun is shining through the clouds."
    "The cherry blossoms are in full bloom, their pink petals creating a beautiful contrast against the blue sky."
    "Kasuka is holding the umbrella, but she isn't using it."
    "Instead, she's letting the sun warm her face and the breeze play with her hair."
    "She looks happy, and for the first time in a long time, I feel a sense of peace."
    "We walk together through the park, the sound of our footsteps mingling with the rustling of the cherry blossom petals."
    "We don't say anything, but that's okay."
    "Sometimes, words aren't necessary."
    "We just enjoy each other's company, the simple pleasure of being together."
    "As we reach the edge of the park, Kasuka turns to me and smiles."
    k "Thank you for walking with me, Hiroshi. It was nice to have someone to talk to."
    main "Thank you too, Kasuka. I had a great time."
    "She leans in and gives me a quick kiss on the cheek before turning and walking away."
    "I watch her go, feeling a warmth in my chest that I haven't felt in a long time."
    "As she disappears into the distance, I can't help but feel hopeful for the future."
    "Maybe, just maybe, things are starting to look up."
    "I suddenly wake up, the dream fading away like a memory."
    "Why am I dreaming about her again?"
    "I sit up in bed, the events of the day still swirling in my mind."
    "I can't stop thinking about Kasuka and the strange coincidence of meeting her again."
    "Maybe I'm in love with her?"
    "There is a thing called love at first sight, right?"
    "Or maybe it's just infatuation."
    "I don't know."
    "Forget it."
    "I need to relax and get some rest."
    "Maybe tomorrow will bring some clarity."
    "Goodnight"

# Jump to chapter 1 after chapter 0 end
    jump chapter1





    