# TODO: Add dialogue for this scene (this might take a long time)
# TODO: Add music, sound effects, and background art (Im broke T^T)

label chapter1:
    "Since that day, my life has changed in many ways."
    "The demo with the invenstor went well, and I got a promotion at work."
    "Daichi and Tomo have been more supportive, they even helped me with my project."
    "My draft that I created in the past few weeks has been approved, and I'm excited to see where this journey takes me."
    "However, amidst all these changes, one thing remains constant - my growing feelings for Kasuka."
    "Actually, I haven't met her since that day."
    "That raining day feels like a distant memory now."
    "Right now I'm really don't care about that day anymore."
    "I just want to see my project succeed"
    "By the way, I got my salary right now, it's quite a lot of money for a student like me."
    "Recently, I have bought a lot of things for myself, like a new laptop, a new phone, and some clothes."
    "But I still have some money left, maybe saving it for something special."
    "Anyway, I should go home now, it's already 6 PM."
    t "Hey, Hiroshi! Do you want to grab some dinner together?"
    m "Yeah, let's go! I'm starving."
    d "Sure, I could use a break from work."
    "We decided to go to a nearby restaurant for dinner."
    "After dinner, we chatted about work and life in general."
    "Daichi got promoted to a manager position, and Tomo got promoted to a senior developer."
    "That is great news for them, I'm happy for them."
    "And to celebrate, Tomo suggested we go for drinks after dinner."
    "We had a great time, laughing and sharing stories."
    "After a few drinks, we decided to call it a night and head home."
    main "Tonight was fun, we should do this again sometime."
    d "Definitely, let's plan something soon."
    t "Agreed, it's always good to unwind after a long week."
    main "Yeah, I had a great time too. Thanks for inviting me."
    "As we parted ways, I couldn't help but feel grateful for having such great friends."
    "I walked home alone, enjoying the cool night air and the sound of my footsteps on the pavement."
    "Actually, tonight is quite cold, I should have brought a jacket."
    main "I think I should buy a jacket right now, it's getting colder."
    "Luckily, there is a clothing store on the way home."
    "The store is still open, I remember seeing some jackets on display."
    main "Wow, this jacket looks nice and warm."
    main "And it's on sale too, I should buy it."
    "I walked into the store and picked out a jacket that I liked."
    "1400 yen, that is pairly cheap for a jacket."
    "Am I got scammed?"
    main "Whatever, I need a jacket right now."
    "I paid for the jacket and left the store, feeling much warmer already."
    "I look up at the sky, it's still cloudy, but at least it's not raining anymore."
    "It's 8 PM now, the city lights are shining bright, and the streets are bustling with people."
    main "I wonder if I have something to do tonight"
    main "Return home right now is quite boring."
    main "Oh yeah, I see on the social media that there is a new snack shop that just opened. It's got great reviews."
    main "I think I should check it out."
    "The snack shop is not far from my house, just a 10-minute walk."
    "When I arrived, the shop was still open, and there were a few customers inside."
    main "Wow, this place looks nice."
    main "I wonder what kind of snacks they have."
    "I walked into the shop and looked around."
    main "Hmm, everything looks so delicious."
    main "I think I will try the love jam, it looks interesting."
    "Although I have never heard of it before."
    "I ordered a jar of love jam and a cup of tea."
    "The shop owner was friendly and chatted with me while I waited for my order."
    "Shop Owner" "So, what brings you here tonight?"
    main "I just wanted to try something new, and I heard great things about your shop."
    "Shop Owner" "Well, I'm glad you did. The love jam is one of our most popular items."
    "After a few minutes, my order was ready."
    "I paid for my order and left the shop, excited to try the love jam."
    main "Maybe I should go somewhere to sit, I'm kinda tired."
    "There is a park nearby, I think I will go there."
    "The park is quiet and peaceful"
    "This is the park I used to come when I was a kid."
    "That is reminiscing."
    "I sat on a bench and took out the jar of love jam."
    "I opened the jar and took a spoonful of the jam."
    main "Urrgghhhh....this is... sweet and sour."
    main "Honestly, I don't know I can describe the taste."
    main "But I don't hate it."
    "After many bites, I realized that I cannot stop eating it."
    "This is quite addictive for some reason."
    "I finished the entire jar of love jam and felt a bit guilty about it."
    main "I should buy another jar next time."
    "As I sat there, enjoying the peacefulness of the park, I couldn't help but think about today"
    main "Today is fun, no wonder I feel so happy."
    main "But when did I go to play with my friends last time?"
    "I can't even remember."
    "Maybe when I was in high school?"
    "Or maybe even earlier?"
    "I guess I have been too focused on work and school lately."
    main "I should make more time for myself and my friends."
    main "And this studio project, I need to make it a success."
    "Lost in my thoughts, I didn't notice the time passing by."
    "I look up at the sky, it's already 10 PM."
    main "Damn....how time flies."
    main "I should head home now, it's getting late."
    "I stood up and stretched, feeling a bit stiff from sitting for so long."
    "Just before I left the park, I saw a person sitting on a bench nearby."
    "I think based on the silhouette, it is a girl."
    "She looks kinda young, maybe around my age."
    "She is wearing a hoodie and has her head down, maybe she is cold."
    "But is 10 PM, why is she here alone?"
    "I think I should go and check on her."
    main "Excuse me, are you okay?"
    r "....."
    main "It's quite late, and it's cold outside. Why are you here alone?"
    r "I....'m fine, just leave me alone."
    "Her face is still hidden under the hoodie, but I can see a few tears rolling down her cheeks."
    "Is she crying?"
    main "Hey, it's okay. You can talk to me if you want."
    r "I...I just feel so lost and alone."
    main "I understand how you feel. Life can be tough sometimes, but you're not alone."
    main "If you ever need someone to talk to, I'm here for you."
    r "Thank you...that means a lot to me."
    main "No problem. Do you want me to walk you home or somewhere safe?"
    r "Yes, please. I don't feel safe here alone."
    main "Alright, let's go."
    "I walked with her to a nearby convenience store, where she could call someone to pick her up."
    r "Thank you for helping me. I don't know what I would have done without you."
    main "You're welcome. Just remember, you're not alone."
    r "I will. Thank you again."
    "After she called someone to pick her up, I watched as she got into a taxi and drove away."
    main "I hope she will be okay."
    "I walked home, feeling a bit better about myself for helping someone in need."
    main "Arrggghhh...I forgot to ask her name."
    main "Whatever, I just want to go home and sleep right now."
    "When I arrived home, I felt a sense of relief wash over me."
    "I took off my jacket and sat down on the couch, feeling exhausted but content."
    main "Today was a good day."
    main "I should get some rest now, I have a big day tomorrow."
    "I went to bed, feeling grateful for the small moments of kindness and connection that make life worth living."
    "As I drifted off to sleep, I couldn't help but think about the girl I met today."
    main "I wonder who she is."
    main "Maybe I will see her again someday."
    "With that thought, I closed my eyes and let myself fall into a peaceful slumber."
    jump a_surprise

label a_surprise:
    t "Hiroshi! I got a task for you."
    "Since I got promoted, my workload has increased significantly."
    "But my salary and benefits have also improved."
    "I guess that is the trade-off."
    "I quite used to my old workload, but I have to adapt to the new one."
    "But you cannot survive in this world without adapting."
    main "Sure, what do you need help with?"
    t "I need you to prepare a presentation for our next meeting with the investors."
    "Oh no, not another presentation."
    "I have done so many presentations in the past few weeks."
    "Most of them are about our studio project."
    "But I guess I have no choice."
    "Beside, this is a great opportunity for me to showcase my skills and impress the investors."
    main "Alright, I'll get started on it right away."
    t "Thanks, Hiroshi. I knew I could count on you."
    "I spent the next few days working on the presentation, staying up late and putting in extra effort to make it perfect."
    "I don't remember how many cups of coffee I drank to stay awake."
    "I feel kinda dizzy and tired all the time."
    "But finally, the day of the presentation arrived."
    "I practiced my presentation several times, making sure I knew my material inside and out."
    "I choose a a suit that I bought recently to wear for the presentation."
    "It was kinda expensive, but I wanted to make a good impression."
    "Today is a big day for me."
    "I mean a big day for my career."
    "I arrived at the office early, feeling nervous but excited."
    "I look up at the sky, it's shinny and clear."
    "I think the weather is perfect for a presentation."
    main "Okay, I can do this."
    "I took a deep breath and walked into the conference room, where the investors were waiting."
    main "Good morning, everyone. Thank you for taking the time to meet with us today."
    "I began my presentation, speaking clearly and confidently."
    "I explained our studio project, highlighting its unique features and potential for success."
    "The investors listened attentively, asking questions and providing feedback."
    "I answered their questions to the best of my ability, feeling more and more confident as I went along."
    "After what felt like hours, I finally finished my presentation."
    main "Thank you for your time and consideration. I look forward to hearing your feedback."
    "The investors applauded, and I felt a sense of relief wash over me."
    "I had done it."
    "I had successfully presented our studio project to the investors."
    "After the presentation, the investors approached me, praising my work and expressing interest in our project."
    "I felt a sense of pride and accomplishment, knowing that my hard work had paid off."
    t "Hiroshi, you did an amazing job! I'm so proud of you."
    d "Yeah, you really nailed it. I knew you could do it."
    main "Thanks, guys. I couldn't have done it without your support."
    "I feel like all of my hard work had finally paid off."
    "I really happy right now."
    main "You guys don't mind if I can take some time off, do you?"
    t "Of course not, you deserve it after all the work you've done."
    d "Yeah, take all the time you need."
    main "Thanks, I think I will go to the park and relax for a bit."
    "I walked to the park, enjoying the warm sunshine and the sound of birds chirping."
    "I met awesome co-worker there, everyday is a fun day with them."
    main "I want to eat that love jam again."
    "I went to the snack shop and bought another jar of love jam."
    "But this time, I bought a lot of it"
    "To be honest, it is quite addictive."
    "I also bought some snacks for my co-workers, they might like it."
    "I walked to the park and sat on a bench, enjoying the peacefulness of the surroundings."
    "As I ate the love jam, I couldn't help but think about Kasuka."
    main "I wonder what she's doing right now."
    main "I haven't seen her since that day."
    "Since that day, we haven't talked or seen each other."
    "Maybe she is avoiding me."
    "Or maybe she is just busy with her own life."
    main "Oh no, I shouldn't think like that."
    main "I think she has her own life to live."
    main "I should focus on my own life too."
    "Just then, I heard a voice"
    ri "Hiroshi! Is that you?"
    main "Riku? Wow, it's been a while."
    ri "Yeah, it's been a long time. How have you been?"
    main "I've been good, just busy with work and school. How about you?"
    ri "Same here, just trying to keep up with everything."
    "By the way, this is Riku Amatsukaze, my childhood friend."
    "We somehow worked at the same company, same studio."
    "But to be honest, we don't talk much at work."
    "Maybe I'm too busy with my own stuff."
    "And we don't meet each other after I got moved to Tokyo."
    ri "So, what brings you to the park today?"
    "Now I looked at her, Riku turns to be a very cute girl."
    "I mean, she is cute when we were kids, but now she is even cuter."
    "Her hair is longer, and she has a more mature look."
    "How on earth did I not notice that before?"
    "Maybe that time I was just a kid,"
    "And the thing I only care about was playing games and eating snacks."
    "Learning as well, I guess."
    main "I just finished a big presentation at work, and I wanted to relax for a bit."
    ri "You mean the one for the investors?"
    main "Yeah, that one. It went well, thanks for asking."
    ri "That's great to hear! I'm glad it went well."
    main "Definitely. It was a lot of work, but it paid off."
    main "Though I feel kinda tired right now."
    main "I think I stayed up too late preparing for the presentation."
    ri "I can imagine. Presentations can be stressful."
    main "Yeah, but it's all worth it in the end."
    ri "So, what are you doing now? Just relaxing?"
    main "Yeah, just enjoying the park and eating some love jam."
    ri "?"
    main "I don't know if I can describe the taste, but it's quite addictive."
    ri "Love jam? I've never heard of that before."
    main "It's a new snack that I discovered recently. You should try it sometime."
    "I think more like a jam that makes you love it."
    "A snack is not really a snack if you don't love it, right?"
    "Please tell me I'm not the only one who thinks like that."
    ri "Haha, I guess you have a point there."
    main "Want to try some?"
    ri "I think I will pass for now. I'm not really a fan of sweet things."
    main "But I thought you like sweets? Like children do?"
    ri "I'm not a child anymore, you know."
    main "Haha, fair enough."
    "We chatted for a while, catching up on each other's lives."
    "Riku told me about her job and her hobbies, and I shared some stories about mine."
    "It was nice to reconnect with an old friend."
    main "It's great to see you again, Riku."
    ri "You too, Hiroshi. We should do this again sometime."
    main "Definitely. Let's not wait so long next time."
    ri "Ahhhh....I forgot this"
    main "What is it?"
    ri "There is a good new and a bad news. Which one do you want to hear first?"
    main "Hmm, let's go with the good news first."
    ri "Okay, the good news is that you know the FLYWINGS corporation, right?"
    main "Yeah, of course. They are one of the biggest gaming companies in Japan."
    ri "We have a meeting with them next week."
    main "Not again...."
    main "I had so many meetings with investors recently."
    main "I don't think I can handle another one."
    ri "Don't worry, it's not for you. It's for our team lead."
    main "Oh, that's a relief."
    "I sighed in relief, feeling grateful that I wouldn't have to go through another stressful meeting."
    "If that happens, I might just quit my job and become a monk."
    "That is a bad idea, I guess."
    ri "But the bad news is there is a Friday Bento Swap event next week."
    main "?"
    ri "You don't know what a Bento Swap is?"
    main "Absolutely not."
    ri "It's a fun event where everyone brings a homemade bento and swaps it with someone else."
    main "That sounds interesting. But why is it bad news?"
    ri "Because you have to make a bento for someone else."
    main "......................"
    ri "Ahahaha, beside, you have to swap to a girl."
    main "What? Why?"
    ri "Because it's more fun that way. You get to try different kinds of food and maybe even impress someone."
    main "Who created this rule....?"
    ri "I don't know, but it's been a tradition in our studio for a while now."
    main "I see. Well, I guess I have no choice but to participate."
    ri "Sweet! I can't wait to see what you come up with."
    main "But don't expect too much from me. I'm not exactly a master chef."
    "I'm a game developer, not a cook."
    ri "Haha, don't worry. I'm sure whatever you make will be great."
    main "I don't think that is the case."
    main "Whatever, I return to the office right now."
    ri "Alright, see you later, Hiroshi."
    main "See you, Riku."
    "We said our goodbyes and went our separate ways."
    "As I walked back to the office, I couldn't help but feel a bit anxious about the Bento Swap event."
    main "I have no idea what to cook."
    main "Maybe I should look up some recipes online."
    main "But I don't have much time, the event is next week."
    main "I guess I will just have to wing it."
    "I arrived back at the office, feeling a bit more relaxed after my time in the park."
    "I sat down at my desk and started working on some tasks, trying to push the Bento Swap event out of my mind."
    "But I can't"
    main "I can't stop thinking about it."
    main "I need to come up with a plan."
    "The next few days passed in a blur of work and preparation for the Bento Swap event."
    "I scoured the internet for recipes, trying to find something that was both delicious and easy to make."
    "I even went to the grocery store a few times, picking out ingredients and supplies."
    "I practiced making the bento a few times, trying to get it just right."
    "I don't want to mess this up."
    "I'm try to make omurice, a Japanese dish that consists of an omelette filled with fried rice and topped with ketchup."
    "Although it is a simple dish, but it is not easy to make."
    "I don't know how many times I have failed to make it."
    "Wasted so many eggs"
    "Luckly, eggs are quite cheap."
    "If this is something expensive, I might go bankrupt."
    "But finally, after many attempts, I managed to make a decent omurice."
    "The taste is not perfect, but it is edible."
    "Although I don't know edible is a good thing or not."
    "I packed the omurice into a bento box, adding some side dishes and decorations to make it look more appealing."
    main "I still don't know who I will swap with."
    main "Maybe with Riku? She is a great cook after all."
    main "But I don't want to swap with her, she might judge my cooking skills."
    "I can image her reaction."
    ri "Hiroshi, did you make this yourself?"
    ri "It's...interesting(?)"
    ri "I guess it's edible(?)"
    main "Damn it, I don't want to hear that."
    "I don't want to think about it anymore."
    main "How about Kasuka?"
    main "She is a great cook too."
    main "But I don't know if she will like my cooking."
    main "What if she hates it?"
    main "What if she thinks I'm a terrible cook?"
    main "What if she never talks to me again?"
    "I don't want to think about it anymore."
    main "I just want to get through this event."
    main "Forget about it."
    "Finally, the day of the event arrived."
    "Today is Friday."
    "Normally, I would be excited for the weekend."
    "Because I can relax and do whatever I want."
    "But today, I feel a bit anxious."
    "I don't know what to expect from the event."
    "I arrived at the office early, feeling a bit nervous but also excited."
    "The office was decorated with colorful banners and balloons, creating a festive atmosphere."
    "I can still see the a whiteboard in the corner still reads “FIX THE DAMN WATER PHYSICS,”"
    "That is kinda funny."
    main "What on earth is this decoration for?"
    "I looked around, seeing my co-workers chatting and laughing, holding their bento boxes."
    "My brain is still trying to process the situation."
    "But unfornately, my brain failed."
    "The only thing I can understand is I don't understand anything."
    "Tomo and Daichi came over to me, holding their bento boxes."
    t "Hey, Hiroshi! Ready for the Bento Swap?"
    d "Yeah, let's see what you've got!"
    main "................"
    main "I don't know if I'm ready for this."
    t "Come on, it'll be fun! Just relax and enjoy the food."
    d "Yeah, and who knows? You might even find a new favorite dish."
    main "I hope so."
    "We all sat down at a long table, placing our bento boxes in front of us."
    "The room was filled with the sound of chatter and laughter, as everyone eagerly opened their bento boxes and took their first bites."
    "I opened my bento box, feeling a bit nervous."
    "I looked around the table, seeing all the different dishes that my co-workers had made."
    "There were sushi rolls, tempura, teriyaki chicken, and even some homemade desserts."
    "I felt a bit intimidated, wondering if my omurice would measure up."
    "Just then, Kasuka walked into the room, holding her own bento box."
    main "Oh no, she is here."
    main "I hope she doesn't swap with me."
    k "Hey, everyone! Sorry I'm late."
    "Oh by the way, Kasuka is working in the same studio as us."
    "She is a great designer, she helps to design characters and backgrounds for our games."
    "That is one of the reasons why our studio project looks so good."
    "She is also very kind and friendly, always willing to help out her co-workers."
    "But we never really talk much."
    "Since that day"
    "I don't know why, but I feel a bit nervous around her."
    main "Okay, just stay calm."
    main "You can do this."
    t "Hey, Hiroshi! You seems spaced out."
    d "Yeah, are you okay?"
    main "Yeah, I'm fine. Just a bit nervous, I guess."
    t "Don't worry, just relax and enjoy the food."
    d "Yeah, and remember, it's all about having fun."
    "I don't know if feeling nervous is fun or not."
    "I took a deep breath and tried to calm myself down."
    "Just then, Kasuka sat down next to me, placing her bento box in front of her."
    main "Oh no, she is sitting next to me."
    main "Please don't swap with me."
    k "Hey Hiroshi, you are quiet today. Everything okay?"
    main "Was I supposed to be loud?"
    "I shrug"
    k "Haha, just kidding. I know you can be a bit shy sometimes."
    main "Yeah, I guess so."
    k "So, what did you make for the Bento Swap?"
    main "I made omurice."
    k "Oh, that sounds delicious! I love omurice."
    main "Really?"
    k "Yeah, it's one of my favorite dishes."
    main "That's..... good to hear."
    "What a relief."
    main "What about you? What did you make?"
    k "Me? Check this out."
    "She lifts the lid of her bento box, I cannot stop looking at it."
    "Inside, there is a perfectly rolled tamagoyaki, its yellow spirals catching the light"
    "It is beautiful."
    "Beside it, edamame pods are aligned with mathematical precision, and delicate slices of pickled daikon are carved into petals"
    "Even the rice is stamped with a single red umeboshi in its center"
    "That is a whole new level of bento artistry."
    main "Wow, Kasuka, this looks amazing."
    k "Thanks! I spent a lot of time making it."
    main "I can tell. You have a real talent for this."
    k "So....what do you guys think of my bento?"
    "I think she want to hear our opinion."
    t "It's incredible, Kasuka. You really outdid yourself."
    d "Yeah, it's like a work of art. I don't even want to eat it."
    k "Haha, thanks guys. I'm glad you like it."
    main "Yeah, it's really impressive."
    main "I wish I could make something like that."
    k "You can, Hiroshi. It just takes practice."
    main "Maybe one day."
    "We all laughed and continued"
    "I guess it not that bad after all."
    k "Oh right, Hiroshi, I almost forgot."
    main "Forgot what?"
    "Honestly, I don't want to know."
    k "I was going to ask if you wanted to swap bentos."
    main "Urrghghghghghghg........"
    "Please no, please no, please no."
    "I can imagine her reaction."
    k "So you called it omurice, right?"
    k "I think is edible....."
    k "Kinda interesting texture."
    "......."
    "I don't want to hear that."
    main "Are you sure you want to swap with me? I dont think my cooking is that good."
    k "Don't be silly, Hiroshi. I'm sure it's delicious."
    k "Besides, it's all about the fun of trying new things, right?"

# Scene 2: Friday Bento Swap

# Choices for Scene 2

label bento_reaction:
    menu:
        "I guess so": # Kasuka is a great cook after all
            $ kasuka_affection += 1
            jump chapter1_a
        "I'm not really into homemade stuff.": # I'm disappointed......
            jump chapter1_b

label chapter1_a:
    main "Yeah, I guess so."
    main "Let's swap."
    "As we swap bentos, I try to smile — but then something falls from her box."
    "A small folded piece of paper flutters to the table."
    "I pick it up. It's covered in neat handwriting... but something catches my eye."
    main "...Is this yours?"
    k "Oh! Wait — that wasnt supposed to be—!"
    "I glance down. Its... code?"
    "`// Day 103: Still feel like no one sees the small things I do.`"
    "`// Pretending it doesn't matter is exhausting.`"
    "I look up. Kasuka looks frozen, wide-eyed."
    k "It's just... something I write. You know. Like... journaling."
    main "In code?"
    k "Yeah. I guess it's easier that way. Feels safer."
    "The room goes quiet. She's not joking. She's serious."
    "For the first time, I see something behind her smile — a tiredness."
    "A silence hangs in the air."
    "She quickly snatches the paper back and tucks it into her bag."
    k "Sorry, that was weird. Forget it."
    main "...It's not weird."
    k "...Thanks."
    "Her voice is softer now. Less upbeat. More real."
    t "Hey guys, are you okay?"
    k "Yeah! Totally. Just... bento talk."
    "She forces a smile, but I notice her glance at the paper once more."
    "And I realize... maybe she wanted someone to see it after all."
    "I feel a pang of guilt."
    "The situation is heavier than I expected."
    "I have to change the subject."
    main "So, you said you love omurice?"
    k "I love omurice, so I'm excited to try yours."
    "I watched as Kasuka took her first bite of my omurice."
    "Please like it, please like it, please like it."
    k "Hmm....Huh......Huh ?"
    "I think I ready to die right now."
    "Based on her reaction, she doesn't like it."
    k "It's...interesting(?)"
    "I KNEW IT"
    k "I guess it's edible(?)"
    "PLEASE DON'T SAY THAT"
    k "So you called it omurice, right?"
    "PLEASE KILL ME NOW!!!!! I DON'T WANT TO LIVE ANYMORE"
    main "Yeah, that's what I called it."
    k "Well, it's definitely unique."
    k "But it's quite good, in a weird way."
    k "I like the sweet and savory combination."
    main "Really?"
    k "Yeah, it's not something I would normally eat, but it's growing on me."
    main "That's..... good to hear."
    "What a relief."
    "Finally, I can breathe again."
    k "So, what do you think of my bento?"
    main "I cannot complain, it looks amazing."
    main "You have a real talent for this."
    main "I can't even compare it to mine."
    k "Haha, you are overreacting."
    k "But thanks, I do enjoy cooking."
    main "Maybe you can teach me sometime"
    main "I think I need to start learning how to cook."
    "Since you never know when you will need to cook for someone special."
    "Or just basically, you need to survive in this world."
    jump chapter1_common_1

label chapter1_b:
    main "I'm not really into homemade stuff."
    main "So I think you should swap with someone else."
    main "I can enjoy my omurice alone."
    k "Oh, okay. I understand."
    k "Sorry if I made you uncomfortable."
    main "No, it's not that"
    main "I just feel my cooking is not that good."
    main "I don't want to disappoint you."
    k "Hiroshi, don't be silly. I'm sure it's delicious."
    k "Besides, it's all about the fun of trying new things, right?"
    main "I hope so, I think I will pass for now."
    k "Alright, no worries. Maybe next time."


    jump chapter1_common_1

label chapter1_common_1:
    "We continued to eat our bentos, chatting and laughing with each other."
    "Despite my initial anxiety, I found myself enjoying the event."
    "It was a fun way to bond with my co-workers and try new foods."
    "As the event came to a close, I felt a sense of camaraderie with my team."
    "Today is a good day."
    "I'm not regretting coming to work today."
    "Actually,I feel I want to come more often."
    "I rest at the charge room, drinking some tea and chatting with my co-workers."
    "Kasuka and the others are cleaning up the mess from the event."
    main "I'm sure they won't need my help."
    main "I think I will just relax here for a bit."
    "After the plates clear, Kasuka closes her box and tucks her chopsticks into a cloth pouch"
    "She turns to me, a small smile on her lips."
    k "Thanks for comming to the event, Hiroshi."
    main "No problem, it was fun."
    main "I really enjoyed trying everyone's bento."
    k "I'm glad to hear that!"
    k "It's always nice to share food with friends."
    main "Yeah, it is."
    "We remained silent for a moment, sipping our tea."
    "What is this awkward silence?"
    main "By the way, Kasuka, I wanted to ask you something."
    k "Sure, what is it?"
    main "What do you want to be when you grow up?"
    k "I'm actually grown up ?"
    main "No no, I mean when you are child."
    k "Oh, I see. Well, when I was a kid, I wanted to be a manga artist."
    main "Really? That's cool."
    k "Yeah, I loved drawing and creating stories."
    k "But as I got older, I realized that it was a tough industry to break into."
    k "So I decided to pursue a career in game design instead."
    "She is not wrong, to be honest."
    "The manga industry is quite competitive, and it can be hard to make a living as a manga artist."
    "But I guess if you are passionate about it, you can make it work."
    "That logic applies to everything in life" 
    main "I see....."
    main "So, why did you choose game design?"
    k "Well, I still love creating stories and characters."
    k "And I think games are a great way to do that."
    k "Plus, I get to work with a team of talented people, which is really rewarding."
    main "That makes sense."
    "I think we are the same boat."
    "Since I joined this studio, I have met so many talented people."
    "This encourages me to work harder and improve my skills."
    "And now I got a chance to work on a project that I'm really passionate about."
    main "I feel like I'm finally doing something that I love."
    k "That's great, Hiroshi........."
    "Why is she hesitating?"
    main "Can I see your manga?"
    k "My manga?"
    k "Why so suddenly?"
    "Why is she flustered?"
    main "I just want to see it."
    main "I mean, if you don't mind."
    k "Well, I haven't drawn in a while."
    k "But I guess I could show you."
    k "It's not very good, though."
    main "I'm sure it's great."
    main "I'd love to see it."
    k "Maybe another time,....... I have to return home now. Good evening, Hiroshi."
    main "Ahhhh.....Good evening, Kasuka."
    "Why is she in such a hurry?"
    "I cannot understand her."
    "Girls are so complicated."
    t "Hey, Hiroshi! Are you coming home with us?"
    main "I think I will pass for now."
    main "Maybe after the meeting with the FLYWINGS CEO."
    t "Alright, suit yourself. See you later, Hiroshi."
    d "Yeah, see you later."
    main "See you, guys."
    "They waved goodbye and left the office, leaving me alone."
    "I remain silent for a moment, sipping my tea."
    "This tea is more bitter than I thought."
    "Actually, very bitter."
    "I'm not a fan of bitter tea."
    "Remaining silent, I think of today's events."
    main "That was fun."
    main "I should do this more often."
    main "But I still don't know who I will swap with next time."
    "I guess I will just have to wait and see."
    "As I finished my tea, I felt a sense of contentment wash over me."
    "Today was a good day."
    "I had fun at the Bento Swap event, and I got to know my co-workers better."
    "I felt grateful for the opportunity to work with such a talented and friendly team."
    "I stood up and stretched, feeling a bit tired but also satisfied."
    main "I think I will head home now."
    main "I have a big day tomorrow."
    "As I walked out of the office, I couldn't help but think about Kasuka's manga."
    main "I wonder what it looks like."
    main "Maybe I should ask her again sometime."
    "With that thought, I headed home, feeling hopeful and excited for the future."
    jump ceo_daughter

# Scene 3: After Work Chat
label ceo_daughter:
    "Finally, the day of the meeting with the FLYWINGS CEO arrived."
    "But why I'm so nervous?"
    "There is a good reason for that."
    "During the weekend, I got a message from Riku."
    ri "You have to come to the meeting with the core team."
    "I turn off my phone, trying to ignore the message."
    "But surely, I cannot ignore it."
    "I have to go to the meeting."
    "Why I'm stuck in this situation?"
    main "Whatever, I think I gain some trust from the investors recently."
    "I nod, trying to convince myself that everything will be fine."
    "I have a curry for breakfast, trying to gain some energy for the meeting."
    "That curry I bought it from a nearby convenience store."
    "The taste is not that bad."
    "BUT IT IS SPICY AS HELL!!!!!!!!!"
    main "I forgot to check the spice level."
    "I quickly drink some milk, trying to cool down my burning mouth."
    main "Why am I eating curry for breakfast?"
    "Normally, no one eat curry for breakfast."
    "But there is a rumor that eating curry can improve your concentration and focus."
    "And it can make you happy as well."
    "I don't know if that is true or not."
    "I just wanted to try something new."
    "But never with a spicy one."
    "I change my clothes, wearing a suit that I bought recently."
    "To be honest, that suit is very good."
    "Somehow it boosts my confidence."
    "I look at myself in the mirror, adjusting my tie and smoothing out any wrinkles."
    main "I'm good now. Let's go."
    "I final check if I forgot anything. And I grab my presentation notes and laptop bag."
    "I head out the door, feeling a mix of excitement and nervousness."
    "The weather is sunny and clear, a perfect day for a meeting."
    "But I cannot enjoy the weather."
    "I have a big responsibility on my shoulders."
    "Right now, I'm scared than ever."
    "Because that is FLYWINGS corporation, one of the biggest gaming companies in Japan."
    "If I mess this up, I might lose my job."
    "Or I become homeless."
    "Thinking about that, I feel a chill run down my spine."
    main "But I have a lot of experience with investors. I can handle this."
    "I'm trying to convince myself that everything will be fine."
    "I arrive at the FLYWINGS headquarters, a towering skyscraper in the heart of the city."
    "I take a deep breath and walk into the building, feeling a bit intimidated by its grandeur."
    "A receptionist greets me"
    "Receptionist " "Hello sir, welcome to FLYWINGS corporation. How can I help you?"
    main "Hi, I'm here for a meeting with the CEO."
    "She checks her computer and nods."
    "Receptionist " "Mr Hiroshi Takanashi, right? Please have a seat. I will help you shortly."
    "I sit down in the waiting area, trying to calm my nerves."
    "Don't be scared, you can do this."
    "That is what I keep telling myself."
    "After a while, the receptionist returns and leads me to a conference room."
    "Inside, I see the CEO of FLYWINGS, a middle-aged man with a sharp suit and an intense gaze."
    "He looks up from his tablet and smiles."
    "CEO " "Ah, Mr Takanashi! It's a pleasure to finally meet you in person."
    main "The pleasure is mine, sir."
    "We shake hands, and I take a seat across from him."
    "CEO " "So, I hear you have some exciting ideas for our next project."
    main "Yes, sir. I have been working on a new game concept that I believe has great potential."
    "I take out my presentation notes and laptop, ready to pitch my ideas."
    "The CEO listens attentively as I explain my concept, highlighting its unique features and potential for success."
    main "I believe this game can appeal to a wide audience, from casual gamers to hardcore fans."
    main "With the right marketing and distribution, I think we can make this a hit."
    "The CEO nods, asking questions and providing feedback."
    "CEO " "Interesting. I like the concept, but I have some concerns about the budget and timeline."
    main "I understand, sir. I have already considered those factors and have a plan in place to address them."
    main "But I believe the potential rewards outweigh the risks."
    "We continue to discuss the project, going over the details and logistics."
    "After what feels like hours, we finally reach an agreement."
    "CEO " "Alright, Mr Takanashi. I am impressed with your ideas and your professionalism."
    "CEO " "I have never met a developer as passionate and dedicated as you."
    "CEO " "I think we can work together to make this project a success."
    "CEO " "We - FLYWINGS corporation - will fund your project and provide the resources you need."
    main "Thank you, sir. I won't let you down."
    "I feel a sense of relief and excitement wash over me."
    "I have successfully pitched my ideas to the CEO of FLYWINGS."
    "I have secured funding and support for my studio project."
    "Maybe this is the start of something great."
    "Today is a very very good day."
    "I cannot think another word to describe it." #Sorry for the bad grammar T^T *dev*
    "While I'm in the conference room, the CEO's daughter walks in."
    r "Dad, I brought you some coffee."
    "CEO " "Thank you, Rin. You always know how to make my day better."
    "Wait a minute, the CEO has a daughter?"
    "But judging to his age, she should be in her late twenties or early thirties."
    "But she looks like a high school student."
    "She has long black hair, tied in a ponytail, and big brown eyes."
    "She is wearing a school uniform, a white blouse and a plaid skirt."
    "She walks over to her father, handing him a cup of coffee."
    "Did I meet her before?"
    "I dont' know why, but she looks familiar."
    "I'm trying to remember where I have seen her before."
    r "Dad, who is this?"
    "She looks at me, her eyes widening in recognition."
    "Now I remember where I have seen her before."
    main "You are the girl from the park."
    r "Errr.....yes, I am."
    "CEO " "Rin, you knew him?"
    r "Yes, we met at the park a few weeks ago."
    main "I didn't know you worked here."
    r "I don't. I'm just visiting my dad."
    r "I was just finishing up some work for school."
    main "I see."
    "CEO " "Rin, this is Mr Takanashi, one of Studio Kairo top developers."
    "CEO " "He has some exciting ideas for our next project."
    r "Studio Kairo? I've heard of that studio before."
    main "Yes, we are working on a new game concept that we believe has great potential."
    r "That's cool. I love games."
    main "Really? What kind of games do you like?"
    r "I like all kinds of games, but my favorite is RPGs."
    main "RPGs? That's interesting. I used to play a lot of RPGs when I was younger."
    r "Yeah, me too. I love the stories and characters."
    main "Maybe you can give me some recommendations sometime."
    r "Sure, I'd love to."
    "We chatted for a while, getting to know each other better."
    "Rin told me about her school and her hobbies, and I shared some stories about mine."
    "It was nice to connect with someone who shares my love of games."
    "After a while, Rin glanced at her watch and stood up."
    r "I should get going. I have a lot of homework to do."
    main "Alright, it was nice meeting you, Amatsukaze."
    r "You too, Takanashi. Maybe we can play some games together sometime."
    main "I'd like that."
    "CEO " "Rin, wait."
    "Rin stopped and turned to her father."
    r "Yes, Dad?"
    "CEO " "Since I'm very busy with work, why don't you let Mr Takanashi take you home?"
    r "WHAT ?!?!?!"
    main "Errr.....I don't think that is a good idea."
    "Definately not a good idea."
    "Who on earth would let a stranger take their daughter home?"
    r "Dad, I don't think that's necessary."
    main "Yeah, I think I will just take a taxi."
    "CEO " "Nonsense. Mr Takanashi is a trusted developer, and I'm sure he will take good care of you."
    "CEO " "Besides, it's a good opportunity for you to get to know someone"
    "CEO " "Since everything you do is go to school, go home and then play games."
    r "Dad, please. I can take a taxi."
    main "Yeah, I think that is a better idea."
    "CEO " "Rin, I'm serious. Mr Takanashi is a responsible adult."
    "CEO " "I trust him, and you should too."
    "Although I'm just 19"
    "Not quite an adult"
    main "If you say so, then I guess I can take you home."
    r "I guess I have no choice....."
    "CEO " "Great! I'll leave you two to it."
    "He stands up and leaves the room, leaving me and Rin alone."
    "We remain silent for a moment, both of us feeling a bit awkward."
    "How many time did I felt to this kind of awkward situation?"
    "I should probably say something to break the ice."
    main "Shall we go?"
    r "Yeah, let's go."
    "We walked out of the conference room, heading towards the exit."
    "As we walked, I couldn't help but feel a bit nervous."
    "I have never been in this kind of situation before."
    "Taking a CEO's daughter home."
    "What if something happens?"
    "What if she doesn't like me?"
    "What if she thinks I'm a weirdo?"
    "I try to push those thoughts out of my mind, focusing on the task at hand."
    r "Sorry to drag you into this, Takanashi."
    main "It's no problem. I'm happy to help."
    r "Thanks. I just don't want to disappoint my dad."
    main "I'm sure you won't. You seem like a responsible person."
    r "I try to be."
    main "What do you mean?"
    r "Well, my dad is always busy with work."
    r "So I have to take care of myself most of the time."
    r "I have to do my own laundry, cook my own meals, and manage my own schedule."
    r "It's not easy, but I guess it makes me more independent."
    main "I see. That must be tough."
    r "Yeah, it is. But I don't mind. I like being independent."
    main "That's a good attitude to have."
    r "hahahaha...."
    ".............."
    "We walked in silence for a while, both of us lost in our own thoughts."
    main "It's a nice day outside."
    r "Yeah, it is, hahahahahah......"
    ".............."
    "This is the most awkward situation ever."
    main "It's kinda early for you to go home, isn't it?"
    r "Yeah, I guess so."
    r "But I have a lot of homework to do."
    r "I think I can finish it in a few hours."
    r "So I can take some time, about 30 minutes to relax."
    main "I see. Do you want to go somewhere?"
    r "Somewhere? Like where?"
    "Here is comes the hard part."
    "When give a suggestion, it has to be a good one."
    "If I suggest a bad one, she might think I'm a weirdo."
    "I mean I'm a weirdo, but I don't want her to think that."
    main "How about a cafe? Cat cafe?"
    r "A cat cafe? What's that?"
    main "It's a cafe where you can play with cats while drinking coffee or tea."
    main "You don't know how popular cat cafes are in Japan?"
    r "No, I don't. But it sounds interesting."
    r "I love cats."
    main "Great! Let's go to a cat cafe then."
    r "Okay, sounds fun."
    "We walked to a nearby cat cafe, not that far from the FLYWINGS headquarters."
    "We are greeted by the sight of several cats lounging around the cafe, some sleeping, some playing with toys, and some even climbing on the furniture."
    "The cafe is cozy and inviting, with soft lighting and comfortable seating."
    r "Wow, this place is so cute."
    "Not hesitating, she walks over to a group of cats, crouching down to pet them."
    "She really loves cats."
    "I can see the joy on her face as she interacts with the cats."
    main "I'm glad you like it."
    r "Yeah, this is the best idea ever."
    main "I will order some drinks for us. What do you want? Don't worry, I will pay for it."
    r "Thanks, Takanashi. I will have a shiny shiny kira kira doki doki matcha latte."
    "......"
    "What the hell is that?"
    main "Errrr...... got it ? "
    "I still don't know what that is."
    "I walk to the counter, trying to remember the name of the drink she ordered."
    main "Sorry, can I have one shiny shiny kira kira doki doki matcha latte?"
    "Am I pronouncing it right?"
    "The barista looks at me, a bit confused."
    "Barista " "I'm sorry, sir. We don't have that drink."
    main "What? You don't have it?"
    "I look at the menu, trying to find the drink she ordered."
    "But there is no such drink on the menu."
    main "Are you sure? My friend ordered it."
    "Barista " "I'm sorry, sir. We don't have that drink."
    main "Damn it, what should I do now?"
    "I don't want to disappoint her."
    main "Can you recommend me something?"
    "Barista " "Sure, we have a lot of great drinks. How about a matcha latte?"
    "I mean it just has matcha in it."
    main "Okay, I will have a matcha latte then."
    main "I will also have a black coffee."
    "Barista " "Alright, that will be 800 yen."
    "That is...."
    "Ridiculously cheap"
    main "Here you go."
    "I hand over the money and wait for our drinks to be prepared."
    "After a few minutes, the barista hands me our drinks."
    "Barista " "Here you go, sir. Enjoy your drinks."
    main "Thank you."
    "I walk back to our table, handing her the matcha latte."
    main "Sorry, they didn't have the drink you ordered."
    r "It's okay, Takanashi. This matcha latte looks good too."
    "She takes a sip of the latte, her eyes lighting up."
    r "Mmm....this is delicious."
    main "I'm glad you like it."
    "Am I imagining things, or she is blushing?"
    "That means she really likes it."
    "I feel a sense of relief wash over me."
    "We continued to chat and enjoy our drinks, the atmosphere in the cafe becoming more relaxed and comfortable."
    "Man, I think I should come to cat cafes more often."
    "Even a weirdo like me can enjoy it."
    r "Sorry Takanashi, I didn't mean to drag you into this."
    main "It's no problem. I'm happy to help."
    "Why is she apologizing?"
    "I don't understand and mind it at all."
    r "Thanks. I just don't want to disappoint my dad."
    main "I'm sure you won't. You seem like a responsible person."
    r "I try to be."
    r "But Takanashi, did you realize something?"
    main "What is it?"
    "I have no idea what she is talking about."
    r "A boy and a girl going to a cat cafe together."
    r "Isn't that a date?"
    "Pfffffffffffff"
    "I almost spit out my drink."
    main "A date? No, it's not a date."
    r "hahahaha.....I knew it."
    r "I think a girl like me cannot have a proper date."
    "She speaks so smallly, almost like she is talking to herself."
    main "What are you talking about?"
    r "Nothing, never mind."
    main "If you say so."
    "We finished our drinks, and I walked her back to home"
    "As we walked, I couldn't help but feel a bit nervous."
    "I have never been in this kind of situation before."
    "Taking a CEO's daughter home."
    "Even myself in the dream, I never thought this would happen."
    "But I guess I did a good job."
    r "Thanks for taking me home, Takanashi."
    main "No problem. It was fun."
    r "Yeah, it was."
    r "Then see you later, Takanashi."
    main "See you, Amatsukaze."
    "We waved goodbye, and I watched as she walked into her luxury apartment."
    "I stood there for a moment, feeling a bit dazed."
    main "I wish I had a house like that."
    main "Maybe one day."
    "With that thought, I headed home, feeling hopeful and excited for the future."
    jump a_suddent_event



# Choices for Scene 3

label a_suddent_event:

label manga_dream:
    menu:
        "You should draw again. I'd love to see your work.": # well well well well well *insert evil laugh*
            $ flag_encourage_draw = True
            $ kasuka_affection += 1
            jump chapter1_c
        "Sound like a lot of work. Maybe another time.":
            jump chapter1_d

label chapter1_c:
    # TODO : Add dialogue for this scene (this might take a long time)
    jump chapter1_common_2

label chapter1_d:
    # TODO : Add dialogue for this scene (this might take a long time)
    jump chapter1_common_2

label chapter1_common_2:
    # Continue the story flow    

# Jump to chapter 2 after chapter 1 end
    jump chapter2